POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "Laptop",
  "price": 50000,
  "description": "Dell Laptop"
}
###

GET http://localhost:5000/api/products
###

DELETE http://localhost:5000/api/products/6a295d6e9199ffcb171fc1aa

GET http://localhost:5000/api/products